#! /bin/bash
# hpc-testing
# Copyright (C) 2025 SUSE LLC
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

test_libfabric()
{
    local host=$1
    local server_ip=$2
    local client_ip=$3

    local run_verbs=1
    local verbs_options=""

    local run_verbs_rxm=0
    local verbs_rxm_options=""

    case $(get_suse_version $host) in
	15|15.1|15.2|15.3|15.4|15.5)
	    verbs_options="-e fi_rma_bw,fi_rdm_cntr_pingpong"
	    ;;
	15.6)
	    verbs_options=""
	    ;;
	15.7|16.0|2025*)
	    verbs_options="-e fi_dgram_pingpong"
	    ;;
        2026*|16.1)
	    verbs_options="-e fi_rma_bw,fi_dgram_pingpong"
            run_verbs_rxm=1
	    verbs_rxm_options="-e fi_dgram_pingpong"
	    ;;
	*)
	    # N/A
	    true
	    ;;
    esac
    if [ $run_verbs -ne 0 ]; then
        tp $host "/usr/bin/runfabtests.sh -v -t short ${verbs_options} verbs $server_ip $client_ip"
    fi
    if [ $run_verbs_rxm -ne 0 ]; then
        tp $host "/usr/bin/runfabtests.sh -v -t short ${verbs_rxm_options} 'verbs;ofi_rxm' $server_ip $client_ip"
    fi
}

